### ISSUE TITLE
I cant build 

### ISSUE THREAD

**Issue by jraynerx** [Lapig/PigPSO2Cam#14]
Can you possibly explain why i cant build this i have tried a few different ways with visual studio and i cant seem to figure it out

**Comment by Lapig** [comment]
I don't know what trouble you could be having just building the project but the source has not been updated since ngs only updated binaries have been released. I figured it's probably for the best to not unleash public lua execution on sega if it's not already out there. 

I'll update the source if that changes but functionally the ngs variant does the same thing just with a new method of executing lua.

**Comment by jraynerx** [comment]
I was having issues with Visual Studio 2022 and dx9 SDK as well installing the SDK. I ran into compile issues related to that. Not only that, but I had hoped to branch off a bit from the source code and use the camera modifications that are being executed to attempt with working on a possible first person or VR mod, as I have only found one mention of an old mod which is well gone now unfortunately. @Lapig
